### ISSUE TITLE
CSS Values and Units Level 4 2022-10-19 > 2023-01-31

### ISSUE THREAD

**Issue by fantasai** [w3cping/privacy-request#104]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- CSS Values and Units Level 4
- URL of spec: https://www.w3.org/TR/css-values-4/

- What and when is your next expected transition?
- **Ideally, CR sometime in the next several months, once open issues about clarifying `url()` and viewport units are sorted out. No rush, but we're now trying to wrap up on this Level.**
- What has changed since any previous review?
- **No previous formal review. See [changes since Level 3](https://www.w3.org/TR/css-values-4/#additions-L3) (which also didn't have formal privacy review)**
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?
- **Yes, at https://www.w3.org/TR/css-values-4/#privacy**
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
- **Your documents should be hosted on w3.org not on github.io per https://www.w3.org/2021/Process-20211102/#tooling**
- **https://www.w3.org/TR/design-principles/**
- Where and how to file issues arising?
- **https://github.com/w3c/csswg-drafts/labels/css-values-4 please tag with [css-values-4]**
- Pointer to any explainer for the spec?
- Nope

Other comments:
None

**Comment by pes10k** [comment]
Closing out the review; no issues to raise, all good!
