### ISSUE TITLE
PNG 3rd edition 2022-10-28

### ISSUE THREAD

**Issue by svgeesus** [w3cping/privacy-request#105]
The Privacy IG prefers groups to complete a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed:
  - Portable Network Graphics (PNG) Specification (Third Edition)
- URL of spec: [This must be a dated version in the TR namespace, not an editor's draft.]
  - https://www.w3.org/TR/2022/WD-png-3-20221025/
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations?  If not, correct that before proceeding further.
  - Yes
- Do you need a reply by a particular date?
  - No
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
  - https://github.com/w3c/PNG-spec/issues/228#issuecomment-1279390248
- Where and how to file issues arising?
  - [PNG-spec GitHub repo](https://github.com/w3c/PNG-spec/issues), preferably one issue per comment
- Pointer to any explainer for the spec?
  - No, this is a maintenance update of an old and widely deployed specification

Other comments:

We are heavily constrained by the excellent backwards compatibility with PNG images since 1994.

We are primarily interested in comments on the [new (or newly-standardized)](https://www.w3.org/TR/png/#changes-since-the-w3c-recommendation-of-10-november-2003-png-second-edition) features

**Comment by AramZS** [comment]
I'm picking up this review to write an assessment.

**Comment by svgeesus** [comment]
Thanks @AramZS any update?

**Comment by AramZS** [comment]
Review was discussed on the PING call, and I have opened an issue to encourage work to be done to make the Privacy Considerations section more extensive. The issue filed as part of this review is at: https://github.com/w3c/PNG-spec/issues/282

Please let me know if I can clarify or help on the issue @svgeesus!

**Comment by pes10k** [comment]
(nvm, @AramZS, looks like the above is sorted and we'll close it out)
