### ISSUE TITLE
Multi-Screen Window Placement 2022-11-25

### ISSUE THREAD

**Issue by anssiko** [w3cping/privacy-request#106]
- name of spec to be reviewed: Multi-Screen Window Placement
- URL of spec: https://www.w3.org/TR/2022/WD-window-placement-20221101/
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations? https://www.w3.org/TR/window-placement/#privacy
- Do you need a reply by a particular date? Prefer a response by EOY 2022.
- Please point to the results of your own self-review: https://github.com/w3c/window-placement/blob/main/security_and_privacy.md
- Where and how to file issues arising? https://github.com/w3c/window-placement/issues/
- Pointer to any explainer for the spec? The following two explainers cover the Multi-Screen Window Placement feature scope in review: [incremental improvements to existing screen information and window placement APIs](https://github.com/w3c/window-placement/blob/main/EXPLAINER.md) and API enhancements to allow [initiation of multi-screen experiences from a single user activation](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md). These explainers should be read in that order.

Other comments:

While Chrome is the early adopter of this API, the specification has been reviewed by Mozilla and Apple in the Second Screen WG with special attention to privacy. Related meeting discussions: Mozilla's feedback during 2022 Q2 virtual meeting [Day 1](https://www.w3.org/2022/06/07-webscreens-minutes.html#t17) and [Day 2](https://www.w3.org/2022/06/08-webscreens-minutes.html#t01) and Mozilla's and Apple's feedback at [TPAC 2022](https://www.w3.org/2022/09/16-webscreens-minutes.html#t06).

We look forward to further improving the [Privacy Considerations](https://www.w3.org/TR/window-placement/#privacy) with your suggestions and feedback. Thank you for your review!

**Comment by pes10k** [comment]
Closing out this review.  Filed two needs-resolution issues:

- https://github.com/w3c/window-placement/issues/120
- https://github.com/w3c/window-placement/issues/121

And two non-needs-resolution (advisory) issues:

- https://github.com/w3c/window-placement/issues/122
- https://github.com/w3c/window-placement/issues/123

**Comment by anssiko** [comment]
@pes10k & PING thanks for your swift privacy review!

FYI @michaelwasserman
