### ISSUE TITLE
CSS View Transitions 2022-11-25

### ISSUE THREAD

**Issue by khushalsagar** [w3cping/privacy-request#107]
- Name of spec to be reviewed: CSS View Transitions
- URL of spec: https://www.w3.org/TR/css-view-transitions-1/
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations?  If not, correct that before proceeding further: Yes
- Do you need a reply by a particular date: No
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973): [self review](https://github.com/WICG/view-transitions/blob/main/security-privacy-questionnaire.md)
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues tagged [css-view-transitions-1]
- Pointer to any explainer for the spec? https://github.com/WICG/view-transitions/blob/main/explainer.md

Other comments:

This review is limited to transitions within the same Document. No new data is made available to script by this feature.

**Comment by pes10k** [comment]
I've filed one non-blocking, non-privacy relevant issue that came up during this review.  I didn't identify any privacy concerns in the spec. I'm going to close this review out

- https://github.com/w3c/csswg-drafts/issues/8486
