### ISSUE TITLE
UI Events Keyboard Events Key Values

### ISSUE THREAD

**Issue by LJWatson** [w3cping/privacy-request#108]
- Name of spec to be reviewed: UI Events Keyboard Events Key Values
- URL: https://w3c.github.io/uievents-key/
- Next transition: to CR, February 2023
- Privacy considerations: https://w3c.github.io/uievents-key/
- Self-review: https://github.com/w3c/uievents-key/issues/57#issuecomment-1301231347
- File issues: https://github.com/w3c/uievents-key/issues/

**Comment by pes10k** [comment]
No issues identified, i think all good to go PING/privacy-review side.  Thanks!

**Comment by LJWatson** [comment]
With thanks @pes10k, your review is appreciated as always.
