### ISSUE TITLE
UI Events Keyboard Events Code Values 2022-11-29 2023-01-31

### ISSUE THREAD

**Issue by LJWatson** [w3cping/privacy-request#109]
- Name of spec to be reviewed: UI Events Keyboard Events Code Values
- URL: https://w3c.github.io/uievents-code/
- Next transition: to CR, February 2023
- Privacy considerations: https://w3c.github.io/uievents-code/#privacy
- Self-review: https://github.com/w3c/uievents-code/issues/35#issuecomment-1301310761
- File issues: https://github.com/w3c/uievents-key/issues/

**Comment by pes10k** [comment]
No issues identified, i think all good to go PING/privacy-review side.  Thanks!

**Comment by LJWatson** [comment]
Thank you @pes10k, your review is appreciated as always.
