### ISSUE TITLE
Digital Publishing WAI-ARIA Module 1.1 and Digital Publishing Accessibility API Mappings 1.1 2023-02-23 > 2023-04-01

### ISSUE THREAD

**Issue by mattgarrish** [w3cping/privacy-request#116]
- Name of spec to be reviewed:
  - Digital Publishing WAI-ARIA Module 1.1
  - Digital Publishing Accessibility API Mappings 1.1
- URL of spec:
  - https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/
  - https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/
- What and when is your next expected transition?
  - Moving to CR, ideally in April
- What has changed since any previous review?
  - Refer to the change logs for updates since the 1.0 release: https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#changelog and https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/#changelog
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  If not, correct that before proceeding further.
  - Yes, they have the privacy and security sections from the ARIA/Core-AAM specifications as these are just modular extensions
- Please point to the results of your own self-review
  - See the privacy and security sections:
    -  https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#privacy-and-security-considerations
    - https://www.w3.org/TR/2023/WD-dpub-aam-1.1-20230223/#privacy-and-security-considerations
- Where and how to file issues arising?
  - Please open issues for the DPUB-ARIA spec in https://github.com/w3c/dpub-aria/issues and issues for the DPUB-AAM in https://github.com/w3c/dpub-aam/issues
- Pointer to any explainer for the spec?
  - https://www.w3.org/TR/2023/WD-dpub-aria-1.1-20230222/#introduction

Other comments:

The DPUB roles and mappings are only extensions of ARIA that add a set of new roles for publishing. They do not introduce new attributes or features to ARIA.

**Comment by LJWatson** [comment]
Christine asked if I would review these specs on behalf of PING.

Thank you to @mattgarrish and the WG for maintaining usable changelogs, completing the self-reviews, and including privacy considerations in both specifications. These things were helpful.

Other than the noted potential for ARIA to be used to determine that someone is using an assistive technology, I did not find anything of concern in in either specification. That particular concern has been known for more than a decade and has been documented in multiple ARIA specifications, and there is nothing in either of these specifications that is additional cause for concern.

**Comment by mattgarrish** [comment]
Thanks for the review @LJWatson!

**Comment by sandandsnow** [comment]
Closing as review is complete.
