### ISSUE TITLE
Scalable Video Coding (SVC) Extension for WebRTC  2023-04-25 > 2023-05-16

### ISSUE THREAD

**Issue by dontcallmedom** [w3cping/privacy-request#117]
- name of spec to be reviewed: Scalable Video Coding (SVC) Extension for WebRTC
- URL of spec: https://www.w3.org/TR/2023/WD-webrtc-svc-20230417/

- What and when is your next expected transition? mid May 2023 to CR
- What has changed since any previous review?  https://github.com/w3c/webrtc-svc/pulls?q=is%3Apr+is%3Aclosed+merged%3A%3E%3D2020-05-01+-label%3AEditorial+ ([previous review request](https://lists.w3.org/Archives/Public/public-privacy/2020AprJun/0017.html))
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  https://w3c.github.io/webrtc-svc/#privacy
- Please point to the results of your own self-review https://w3c.github.io/webrtc-svc/#privacy
- Where and how to file issues arising? https://github.com/w3c/webrtc-svc/issues
- Pointer to any explainer for the spec? https://github.com/w3c/webrtc-svc/blob/main/explainer.md

Other comments:

**Comment by pes10k** [comment]
This was discussed on the PING call on May 4, 2023 and resulted in the following issues
- https://github.com/w3c/webrtc-svc/issues/91
- https://github.com/w3c/webrtc-svc/issues/92
