### ISSUE TITLE
RDF Dataset Canonicalization 2023-06-09

### ISSUE THREAD

**Issue by philarcher** [w3cping/privacy-request#118]
We have conducted a self-review of our spec [RDF Dataset Canonicalization](https://www.w3.org/TR/2023/WD-rdf-canon-20230609/) and the results can be found at https://github.com/w3c/rdf-canon/issues/70.

Please check our findings.

- Do you need a reply by a particular date?
No, but we're hoping to move to CR in July or August at the latest (i.e. before TPAC)

Other comments:

This is a data processing spec, not an interaction spec, and therefore whether privacy is at risk is a property of the dataset being canonicalized rather than of the canonicalization algorithm itself. However, the need to support selective disclosure in Verifiable Credentials leads to the warning highlighted in our text.

**Comment by npdoty** [comment]
I believe kdenhartog did a review of the data integrity spec, but that no one conducted a separate privacy review of just this canonicalization spec in time for the RDF-CANON CR transition. We are closing for now, although if there is interest or need in reviewing the privacy considerations here, please re-raise.
