### ISSUE TITLE
DAPT 2023-07-31

### ISSUE THREAD

**Issue by nigelmegitt** [w3cping/privacy-request#122]
The Privacy IG prefers groups to complete a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Dubbing and Audio description Profiles of TTML2
- URL of spec: https://www.w3.org/TR/2023/WD-dapt-20230801/ - this is the dated version as requested, but since it is in WD, we may make changes to the undated version from time to time: it is not expected that they will impact on this review though.
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations? Yes
- Do you need a reply by a particular date? Ideally in time for us to consider the response at TPAC 2023.
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973) - https://github.com/w3c/dapt/wiki/Considerations-for-the-Privacy-and-Security-Reviews 
- Where and how to file issues arising? Please raise issues on https://github.com/w3c/dapt/issues 
- Pointer to any explainer for the spec? https://github.com/w3c/dapt/wiki/DAPT-Explained - also the Introduction can be used as a form of Explainer.

Other comments:

We have built, actually or conceptually, on previous privacy reviews for TTML2 and IMSC to inform this.

**Comment by plehegar** [comment]
@AramZS will try to turn this around by the end of month.

**Comment by pes10k** [comment]
Was discussed on PING call on Nov, 2, 2023.  Closing this issue out

https://github.com/w3c/ping/blob/main/summaries/PING-minutes-20231102.md
