### ISSUE TITLE
mathml-core 2024-03-01 > 2024-04-01

### ISSUE THREAD

**Issue by bkardell** [w3cping/privacy-request#130]
- name of spec to be reviewed: mathml-core
- URL of spec: https://www.w3.org/TR/2023/WD-mathml-core-20231127/

- Does your document have an in-line Security Considerations section, ideally one separate from the Privacy Considerations? If not, corrrect that before proceeding further.
  - Yes
  
- What and when is your next expected transition?
  - We'd like to move to CR soon, March ideally.

- What has changed since any previous review?
  - Previously this had a [TAG review](https://github.com/w3ctag/design-reviews/issues/438) while it wasn't yet even properly in a working group. MathML  has a tricky history where MathML 3 was REC for many years, but was underspecified, not well integrated (similar to SVG at one point), lacking implementations, and indeed contained much that was not implemented in any browser at all.  MathML-Core was an effort led by a CG (the WG was defunct) to create a new specification subset which would focus on browsers.  Since then the WG has been rechartered, we have done minor but important spec changes, added more tests, an implementation has shipped in chromium, and some alignments have already started to ship in other browsers.

- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  If not, corrrect that before proceeding further.
  - [Yes](https://www.w3.org/TR/2023/WD-mathml-core-20231127/#privacy-considerations)

- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
   - contained in our [TAG Review](https://github.com/w3ctag/design-reviews/issues/438) under the heading "Security Questionnaire..."  
 
- Where and how to file issues arising?
  - The [mathml-core repo issue tracker](https://github.com/w3c/mathml-core/issues), please.

- Pointer to any explainer for the spec?
  - If helpful https://github.com/w3c/mathml-core/blob/main/docs/explainer.md

Other comments:
  - This is my first attempt at navigating wide review requests as a chair, apologies in advance.  If (very probably) I've failed  somewhere, please help me to do better 🙏

**Comment by pes10k** [comment]
Review complete. No issues identified, closing this out
