### ISSUE TITLE
Accessible Rich Internet Applications 1.3 2024-02-01

### ISSUE THREAD

**Issue by daniel-montalvo** [w3cping/privacy-request#131]
The Privacy IG prefers groups to complete a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed:  Accessible Rich Internet Applications 1.3 
- URL of spec: https://www.w3.org/TR/2024/WD-wai-aria-1.3-20240123/
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations?  If not, correct that before proceeding further. https://www.w3.org/TR/wai-aria-1.3/#privacy-considerations
- Do you need a reply by a particular date? Ideally by 1st March 2024. This is a minor spec update with [Changes](https://www.w3.org/TR/wai-aria-1.3/#changelog) since WAI-ARIA 1.2
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
- Where and how to file issues arising? https://github.com/w3c/aria/issues/new/choose/
- Pointer to any explainer for the spec? https://www.w3.org/WAI/standards-guidelines-aria

Other comments:

**Comment by plehegar** [comment]
* [previous review of ARIA 1.2](https://github.com/w3cping/privacy-request/issues/21), which lead to [Detectability of assistive technology](https://github.com/w3c/aria/issues/1371).

**Comment by daniel-montalvo** [comment]
Hi!

Do you plan to submit review comments?

Can we consider  that resolution in [Detectability of assistive technology](https://github.com/w3c/aria/issues/1371) still stands?

Best.

**Comment by npdoty** [comment]
Apologies for the delay, this request came between a gap in our meetings. I'm looking at the spec (and catching up on the discussion from 1.2 and aria/#1371) now.

**Comment by plehegar** [comment]
(I'm told that the ARIA WG will follow up)

**Comment by npdoty** [comment]
PING discussed. We suspect my open question is unlikely to be a privacy issue, although of course happy to hear feedback from the WG experts.

**Comment by daniel-montalvo** [comment]
Hi @npdoty

Sorry for the late reply on this issue.

We conccur, this is not a privacy issue from our perspective. These updates are based on the ARIA states and properties used by the authors, and are irrespective of whether ATs are running.

Maybe @jnurthen or @spectranaut have

**Comment by npdoty** [comment]
We believe this review is completed now. On the larger ongoing question of what features potentially reveal use of assistive technology, we also think that's worth adding to the priv/security questionnaire generally:
https://github.com/w3ctag/security-questionnaire/issues/157
