### ISSUE TITLE
Ethical Web Principles 2024-03-26

### ISSUE THREAD

**Issue by torgo** [w3cping/privacy-request#132]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Ethical Web Principles
- URL of spec: https://www.w3.org/TR/2024/DNOTE-ethical-web-principles-20240319/

- Current Rec/Note phase? *Wide review request on its way to becoming a W3C Statement*
- What and when is your next expected transition? *sometime over the summer to W3c Statement*
- What has changed since any previous review? *no previous privacy review has been done*
- Please point to the results of your self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973) *as this is a high level principles document, it's not clear to me that it's applicable*
- Where and how to file issues arising? *please raise them on our repo: https://github.com/w3ctag/ethical-web-principles/*
- Pointer to any explainer for the spec? *no explainer other than https://www.w3.org/blog/2019/our-ethics-drive-the-architecture-of-the-web/*

Other comments:

**Comment by torgo** [comment]
Thanks - I've put it on our agenda for next week.

**Comment by rinchen** [comment]
The initial read-through was good from a guiding principals perspective. I ended up creating a [pull request](https://github.com/w3ctag/ethical-web-principles/pull/113) for some grammar items. I support addressing some of the [open issues](https://github.com/w3ctag/ethical-web-principles/issues) filed against the principals as they would extend it and provide clarity. For example, the privacy section does not talk at all about consent. Granted, these are discussed in detail in the separate privacy principals reference.

**Comment by plehegar** [comment]
ok to close.
