### ISSUE TITLE
CSS View Transitions 2 2024-04-02

### ISSUE THREAD

**Issue by noamr** [w3cping/privacy-request#133]
The Privacy IG prefers groups to complete a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: CSS View Transitions 2
- URL of spec: https://drafts.csswg.org/css-view-transitions-2/
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations? Yes
- Do you need a reply by a particular date? No
- Please point to the results of your own self-review: https://github.com/WICG/view-transitions/blob/main/security-privacy-questionnaire-cross-doc.md
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues (use [css-view-transitions-2] label
- Pointer to any explainer for the spec? https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md

Other comments:

**Comment by npdoty** [comment]
Is there a spec to review, or just an explainer?

**Comment by noamr** [comment]
> Is there a spec to review, or just an explainer?

Oops, of course there is. Updated the OP

**Comment by pes10k** [comment]
Closing out. Filed one non-needs-resolution issue (its editorial, and so not privacy focused either)

https://github.com/w3c/csswg-drafts/issues/10283
