### ISSUE TITLE
Pointer Events Level 3 2024-05-21 > 2024-08-21

### ISSUE THREAD

**Issue by patrickhlauke** [w3cping/privacy-request#134]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Pointer Events Level 3
- URL of spec: [This must be a dated version in the TR namespace, not an editor's draft.] https://www.w3.org/TR/2024/WD-pointerevents3-20240318/

- What and when is your next expected transition? Ideally around/after September 2024
- What has changed since any previous review? See the revision history https://www.w3.org/TR/2024/WD-pointerevents3-20240318/#revision-history - broadly, the biggest changes are the addition of two new methods for coalesced and predicted events
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  If not, corrrect that before proceeding further. Yes, we have a combined section https://www.w3.org/TR/2024/WD-pointerevents3-20240318/#security-and-privacy-considerations
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973). I believe these should all be covered in https://www.w3.org/TR/2024/WD-pointerevents3-20240318/#security-and-privacy-considerations - please let me know if anything is missing or if the results need to be formatted/listed in a more specific manner
- Where and how to file issues arising? https://github.com/w3c/pointerevents/issues/
- Pointer to any explainer for the spec? https://www.w3.org/TR/2024/WD-pointerevents3-20240318/#intro

Other comments:

**Comment by patrickhlauke** [comment]
Hello, I was wondering when it's likely for the review to be completed?

**Comment by jyasskin** [comment]
Sorry for taking so long to finish this review. I've filed the two issues that we discussed at the PING meeting today, and we think the rest of the spec looks fine.

- [ ] https://github.com/w3c/pointerevents/issues/517
- [ ] https://github.com/w3c/pointerevents/issues/518

**Comment by patrickhlauke** [comment]
thank you @jyasskin ... we appreciate it!
