### ISSUE TITLE
HTML Ruby Markup Extensions 2024-05-23

### ISSUE THREAD

**Issue by frivoal** [w3cping/privacy-request#135]
- name of spec to be reviewed: HTML Ruby Markup Extensions
- URL of spec: https://www.w3.org/TR/2024/WD-html-ruby-extensions-20240523/
- Current Rec phase: Working Draft, recently restored from having been temporarily discontinued as a Note
- What and when is your next expected transition: no specific date has been decided, but significant changes are not anticipated before CR, and there exist some implementations, so absent new problematic feedback, we may be in a good shape for moving to and beyond CR before long. Autumn maybe?
- What has changed since any previous review? The spec had been discontinued for some years, so any review is at this point ancient. Should be reviewed from scratch.
- Please point to the results of your self-review : https://github.com/w3c/html-ruby/issues/12
- Where and how to file issues arising? Please open individual issues in https://github.com/w3c/html-ruby/issues
- Pointer to any explainer for the spec: The spec is intended to contain its own explainer. Specifically:
  - https://www.w3.org/TR/html-ruby-extensions/#intro gives a general intro to the problem space
  - https://www.w3.org/TR/html-ruby-extensions/#relations gives an high level overview of how this relates to the HTML spec
  - https://www.w3.org/TR/html-ruby-extensions/#diff-html gets into the specifics of the motivations for proposing changes to the HTML model
  - The spec has numerous examples. In particular, https://www.w3.org/TR/html-ruby-extensions/#ruby-compound is an author-centric non-normative section focused on illustrating both how you're supposed to use the markup patterns the spec defines and enables, and why you'd want to.
      
  Also, The i18n group has produced a variety of articles about ruby and its needs over the years, in line with what this spec is defining. https://www.w3.org/International/articles/ruby/markup.en is particularly relevant, but there are more if desired.

  Further, this somewhat old but still relevant blog post covers the why and the what of this design quite extensively: https://fantasai.inkedblade.net/weblog/2011/ruby/

**Comment by pes10k** [comment]
This review was discussed on the June 6th PING call. We did not identify any privacy concerns so closing this issue out
