### ISSUE TITLE
Device Posture API 2024-05-31 > 2024-08-31

### ISSUE THREAD

**Issue by anssiko** [w3cping/privacy-request#136]
- name of spec to be reviewed: Device Posture API
- URL of spec: https://www.w3.org/TR/device-posture/
  - (We use auto-publishing and what you see at TR is appropriate to be reviewed at any time.)
- Current Rec/Note phase? Working Draft
- What and when is your next expected transition? We expect to publish new Working Drafts in the short term. We will assess the readiness for the CR transition when the Origin Trial feedback has been received from early adopters in Q4 2024.
- What has changed since any previous review? This is the first formal privacy review request.
- Please point to the results of your self-review: [self-review results](https://github.com/w3c/device-posture/blob/gh-pages/security-privacy-self-assessment.md)
- Where and how to file issues arising? https://github.com/w3c/device-posture/issues
- Pointer to any explainer for the spec? [Device Posture API explainer](https://github.com/w3c/device-posture/blob/gh-pages/README.md) (for additional material, see [Form Factors explainer](https://webscreens.github.io/form-factors/) for the broader domain and [Foldable APIs Origin Trial](https://developer.chrome.com/blog/foldable-apis-ot) for a developer-oriented explainer)

Other comments:

We noticed the questionnaire on [TR](https://www.w3.org/TR/security-privacy-questionnaire/) is slightly different from the [ED](https://w3ctag.github.io/security-questionnaire/) version. The responses are based on the TR version of the questionnaire that we believe has a joint agreement between PING and TAG. Please let us know if there are specific questions in the ED version that we should consider in addition and we're happy to respond to those as well.

The Device Posture API is available as an [Origin Trial](https://developer.chrome.com/origintrials/#/view_trial/4188910603407982593) from Chrome 125 until 128.

[foldable-devices/demos](https://github.com/foldable-devices/demos) hosts demos of various use cases for the API.

Thank you again for your review and close collaboration with our group!

**Comment by pes10k** [comment]
This review was discussed on the PING call on July 18, 2024. The identified issues are

- https://github.com/w3c/device-posture/issues/152
- https://github.com/w3c/device-posture/issues/153
- https://github.com/w3c/device-posture/issues/154
