### ISSUE TITLE
Vibration API 2024-06-28 > 2024-09-20

### ISSUE THREAD

**Issue by anssiko** [w3cping/privacy-request#138]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Vibration API
- URL of spec: https://w3c.github.io/vibration/ (Why ED? See "Other comments")

- What and when is your next expected transition? After TPAC 2024
- What has changed since any previous review?

Please see the [commit history](https://github.com/w3c/vibration/commits/gh-pages/) for details and the [changes section](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvibration%2Fchanges%2Findex.html#changes) for an overview of the changes since the latest published version. Diff between the [latest published version](https://www.w3.org/TR/2016/REC-vibration-20161018/) and the [staged snapshot](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvibration%2Fchanges%2Findex.html) is available at [htmldiff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FREC-vibration-20161018%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Fw3c%252Fvibration%252Fchanges%252Findex.html).

- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations? Yes
- Please point to the results of your own self-review: https://github.com/w3c/vibration/issues/36
- Where and how to file issues arising? https://github.com/w3c/vibration/issues
- Pointer to any explainer for the spec?
 
This feature predates the explainer era, but its [MDN entry](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API) serves as a good starting point.

Other comments:

Due to complexity of revising a Recommendation under the old process, TR for this specification did not receive these latest updates informed by implementation experience, but they were incorporated into the Editor's Draft instead. This caused some unfortunate confusion among readers not closely watching the specification. To clear this confusion, supported by reinvigorated interest and process improvements for revising a Recommendation, this API is now being revived on the Recommendation Track to allow bringing the updates from the ED back to TR and to allow for further improvements using the modern streamlined publication flow.

Thank you for your review!

**Comment by pes10k** [comment]
This review was discussed on the PING call on July 18, 2024. The identified issues are

- https://github.com/w3c/vibration/issues/42
- https://github.com/w3c/vibration/issues/43

**Comment by anssiko** [comment]
Thank you @pes10k and PING folks! We provided initial responses in the issues and are open to discuss your feedback at TPAC subject to your availability.
