### ISSUE TITLE
Accessibility Conformance Testing (ACT) Rules Format 1.1 2024-07-24

### ISSUE THREAD

**Issue by daniel-montalvo** [w3cping/privacy-request#141]
The Privacy IG prefers groups to complete a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: Accessibility Conformance Testing (ACT) Rules Format 1.1
- URL of spec: https://www.w3.org/TR/2024/WD-act-rules-format-1.1-20240618/
- Does your document have an in-line Privacy Considerations section, ideally one separate from Security Considerations?  If not, correct that before proceeding further. No, but the group is aware of that and is working on it.
- Do you need a reply by a particular date? No, ideally two months from now.
- Please point to the results of your own self-review
    https://github.com/w3c/wcag-act/discussions/578
- Where and how to file issues arising? https://www.github.com/w3c/wcag-act/issues/new
- Pointer to any explainer for the spec? https://www.w3.org/WAI/standards-guidelines/act/

Other comments:

**Comment by sandandsnow** [comment]
Hi. We see you are working on a privacy considerations, please let us know when it is ready for review. Otherwise, no feedback from PING at this stage.

**Comment by sandandsnow** [comment]
Closing, can be re-opened when the privacy considerations draft is available, or a new issue.

**Comment by plehegar** [comment]
Groups is [finishing a PR](https://github.com/w3c/wcag-act/pull/576) to update their draft.

**Comment by plehegar** [comment]
PR got merged
