### ISSUE TITLE
WebXR Device API 2024-08-21 > 2024-10-21

### ISSUE THREAD

**Issue by himorin** [w3cping/privacy-request#142]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: WebXR Device API
- URL of spec: https://www.w3.org/TR/2024/CRD-webxr-20240805/

- What and when is your next expected transition? Expecting to update existing CRS, no specific target date
- What has changed since any previous review? Changes section lists changes from last CRS https://www.w3.org/TR/2024/CRD-webxr-20240805/#changes-from-20220331
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  https://www.w3.org/TR/2024/CRD-webxr-20240805/#security
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973) https://github.com/immersive-web/webxr/issues/1129
- Where and how to file issues arising? https://github.com/immersive-web/webxr/issues/
- Pointer to any explainer for the spec?
  - explainer for whole spec at https://github.com/immersive-web/webxr/blob/main/explainer.md
  - privacy and security explainer at https://github.com/immersive-web/webxr/blob/main/privacy-security-explainer.md

Other comments:

**Comment by rinchen** [comment]
Filed

- https://github.com/immersive-web/webxr/issues/1386
- https://github.com/immersive-web/webxr/issues/1387 - I can't tag this one but this one should be labeled _privacy-needs-resolution_ 
- https://github.com/immersive-web/webxr/issues/1388

@pes10k and I talked about some permissions-related feedback and I felt he was better suited to articulate the concern. I'll leave this ticket open until he has provided that feedback.

**Comment by pes10k** [comment]
just as a heads up @rinchen , i added the tag for you.  Thanks for putting these together

**Comment by rinchen** [comment]
@pes10k Reminder for permissions feedback

**Comment by pes10k** [comment]
thanks for the nudge @rinchen 

I've also filed https://github.com/immersive-web/webxr/issues/1390 (needs resolution)

As best I can tell, i think this request issue can be closed out now (but will wait for you @rinchen to do so, in case there are other things in the air)
