### ISSUE TITLE
Vision for W3C 2024-10-23 > 2024-11-20

### ISSUE THREAD

**Issue by tantek** [w3cping/privacy-request#145]
- name of spec to be reviewed: Vision for W3C
- URL of spec: https://www.w3.org/TR/2024/NOTE-w3c-vision-20241018/

- Current Rec/Note phase? Note
- What and when is your next expected transition? Statement, upon completion of wide and horizontal reviews, and AC vote.
- What has changed since any previous review? No previous review.
- Please point to the results of your self-review No technical security or privacy features.
- Where and how to file issues arising? https://github.com/w3c/AB-public/issues/ and label "needed for Note" if an issue MUST be resolved before publishing an updated Note, or "needed for Statement" if an issue MUST be resolved before publishing a Statement draft for the AC to vote on.
- Pointer to any explainer for the spec? https://www.w3.org/wiki/AB/2025_Priorities#Vision

Other comments:

The minimum horizontal review period of 28 days has been requested. Please feel free to request more time for horizontal review in a comment on this issue.

**Comment by sandandsnow** [comment]
We discussed this request in the first meeting of the Privacy WG. No changes needed.

**Comment by rinchen** [comment]
I independently reviewed this and have no recommended adjustments. My personal opinion: I fully support the message of this document.

**Comment by plehegar** [comment]
Discussed [last week](https://github.com/w3c/privacywg/blob/main/minutes/privacywg-20241107.md#2-open-privacy-reviews).
