### ISSUE TITLE
Several Verifiable Credential Documents 2024-11-01 > 2024-12-01

### ISSUE THREAD

**Issue by iherman** [w3cping/privacy-request#146]
The Verifiable Credentials Working Group[1] is in the process of requesting new CR snapshot publications for a series of documents[1][2][3]:

- https://w3c.github.io/vc-data-integrity/transitions/2024/CR2/
- https://w3c.github.io/vc-di-eddsa/transitions/2024/CR2/
- https://w3c.github.io/vc-di-ecdsa/transitions/2024/CR2/ 
- https://w3c.github.io/vc-data-model/transitions/2024/CR2/
- https://w3c.github.io/vc-jose-cose/transitions/CR2/2024-11-05/

The Working Group would ask for an official horizontal review concentrating on the substantive changes since the last CR snapshots (which were preceded by a horizontal review already). These changes are, respectively: 

- For Data Integrity: First item of https://w3c.github.io/vc-data-integrity/transitions/2024/CR2/#revision-history
- For EdDSA: First item of https://w3c.github.io/vc-di-eddsa/transitions/2024/CR2/#revision-history
- For ECDSA: First item of https://w3c.github.io/vc-di-ecdsa/transitions/2024/CR2/#revision-history
- For Data Model: See items under "Changes since the v2.0 First Candidate Recommendation": https://w3c.github.io/vc-data-model/transitions/2024/CR2/#revision-history
- For Jose-Cose: listed in [3] explicitly

For information, the WG would like to issue these CR snapshots by December. We would appreciate it if your review would be done within that timeframe.

Each document is in its own GitHub repository, we would welcome potential comments there.

Thank you

[1] https://github.com/w3c/transitions/issues/657
[2] https://github.com/w3c/transitions/issues/658
[3] https://github.com/w3c/transitions/issues/660

@msporny @decentralgabe @brentzundel

**Comment by npdoty** [comment]
Reviews from Nick and Kyle both conclude that the particular changes in this case don't appear to make a significant privacy impact.
