### ISSUE TITLE
ARIA in HTML > 2021-04-02

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-request#34]
The Web Applications WG requested a privacy review of ARIA in HTML on [1 March 2021](https://lists.w3.org/Archives/Public/public-privacy/2021JanMar/0024.html).

Link to spec: https://www.w3.org/TR/2021/WD-html-aria-20210301/

Link for filing issues: https://github.com/w3c/html-aria/issues

**Comment by sandandsnow** [comment]
PING will discuss this review on its call on 18 March 2021

**Comment by ShivanKaul** [comment]
I filed https://github.com/w3c/html-aria/issues/295

**Comment by sandandsnow** [comment]
Review discussed on PING call on [18 March 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210318)

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review

Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
