### ISSUE TITLE
Media Capabilities

### ISSUE THREAD

**Issue by sandandsnow** [w3cping/privacy-request#35]
The Media WG has requested a privacy review of Media Capabilities on [26 February 2021](https://lists.w3.org/Archives/Public/public-privacy/2021JanMar/0023.html).

Spec: https://w3c.github.io/media-capabilities/

Security and Privacy considerations section: https://w3c.github.io/media-capabilities/#security-privacy-considerations

Answers to Self-Review: Security and Privacy Questionnaire: https://github.com/w3c/media-capabilities/blob/master/security-privacy-questionnaire.md

Link for raising issues: https://github.com/w3c/media-capabilities/issues

**Comment by sandandsnow** [comment]
PING will discuss this privacy review on its call on 18 March 2021.

**Comment by NalaGinrut** [comment]
Thanks @pes10k

**Comment by NalaGinrut** [comment]
The issue about the review: https://github.com/w3c/media-capabilities/issues/170
@pes10k @plehegar

**Comment by samuelweiler** [comment]
I broke each of the line items from https://github.com/w3c/media-capabilities/issues/170 into separate issues and suggested that the working group close https://github.com/w3c/media-capabilities/issues/170.

https://github.com/w3c/media-capabilities/issues/171
https://github.com/w3c/media-capabilities/issues/172
https://github.com/w3c/media-capabilities/issues/173
https://github.com/w3c/media-capabilities/issues/174
https://github.com/w3c/media-capabilities/issues/175
https://github.com/w3c/media-capabilities/issues/176

**Comment by sandandsnow** [comment]
Review discussed on PING call on [18 March 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210318)

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review

Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
