### ISSUE TITLE
WebCodecs 2021-04-14

### ISSUE THREAD

**Issue by chcunningham** [w3cping/privacy-request#38]
- name of spec to be reviewed: WebCodecs
- URL of spec: https://w3c.github.io/webcodecs/
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  https://w3c.github.io/webcodecs/#privacy-considerations
- Do you need a reply by a particular date? ASAP. Chromium is planning to ship this feature in mid July 2021, with code freeze occuring in late May. This doesn't close the door to changes (and certainly not additions), but providing feedback quickly gives us more opportunity to incorporate it without breaking sites. 
- Please point to the results of your own self-review: https://github.com/w3c/webcodecs/blob/main/security-privacy-questionnaire.md
- Where and how to file issues arising? Please file as new issues in https://github.com/w3c/webcodecs/issues
- Pointer to any explainer for the spec? https://github.com/w3c/webcodecs/blob/main/explainer.md

Other comments:
- Please reach out to me via email (chcunningham@chromium.org) ASAP to setup a virtual meeting (I'll loop in co-editors). The spec is dense with media domain knowledge and I expect a fair bit of in depth discussion. 
- Author feedback from the Chrome origin trial has been very positive and these users are eager to see it ship. This API has generated considerable user excitement ([twitter](https://twitter.com/search?q=webcodecs&src=typed_query&f=live), [discourse](https://discourse.wicg.io/t/webcodecs-proposal/3662))

FYI co-editors: @padenot (Mozilla) and @aboba (Microsoft)

**Comment by npdoty** [comment]
I'm confused by the timeline. The First Public Working Draft was published last week. Review requests today indicate that feedback is necessary ASAP since an implementer plans to freeze their implementation by late May. Elsewhere you indicate that any substantial changes would have to be made "well in advance" of May 20th.

If review feedback takes more than a few days, are any changes likely to be considered as "breaking sites" or are we already past that?

Is the First Public Working Draft intended to be the final version? 

Where did our process go wrong that reviews are being requested at this stage?

**Comment by chcunningham** [comment]
Sorry for the confusion. I think it is totally fine for the review to go on beyond the May 20th date, but I want to encourage that requests for substantial breaking changes be prioritized and arrive as soon as possible. Breaking changes are not ruled out now nor in the future, but they're certainly much easier now. The FPWD is not intended to be the final version, but I expect that the core shape of the API is relatively stable. 

Re: process, we are working to quickly meet demand for this feature, particularly from the RTC space seeking accommodate various pandemic-time needs. Also, I'm new to horizontal reviews. While it seems typical to request upon FPWD, I regret not asking sooner. Apologies.

**Comment by sandandsnow** [comment]
Review discussed on PING call on [6 May 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210506).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review

Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
