### ISSUE TITLE
CSS Multi-column Layout Module Level 1 2021-05-09 > 2021-06-01

### ISSUE THREAD

**Issue by rachelandrew** [w3cping/privacy-request#39]
- name of spec to be reviewed: _CSS Multi-column Layout Module Level 1_
- URL of spec: https://www.w3.org/TR/css-multicol-1/

- What and when is your next expected transition? To CR once I have HR signoff.
- What has changed since any previous review? No previous review that I am aware of
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  As a layout spec, it has no known privacy or security implications. Therefore I used the wording other layout specs have used: https://www.w3.org/TR/css-multicol-1/#priv-sec
- Where and how to file issues arising? https://github.com/w3c/csswg-drafts/issues
- Pointer to any explainer for the spec? none

Other comments: Multi-column layout is a layout specification for taking content and breaking it into multiple columns. This specification was in CR, and was moved back to WD status after a long period of no updates. It is well implemented already in browsers and print user agents.

**Comment by sandandsnow** [comment]
Privacy review to be discussed on next PING call on 3 June 2021

**Comment by sandandsnow** [comment]
Review discussed on PING call on [3 June 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210603)

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review

Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
