### ISSUE TITLE
Requested re-review of privacy issue in CSS Color Adjust 2021-05-13 -> 2021-06-24

### ISSUE THREAD

**Issue by tabatkins** [w3cping/privacy-request#41]
* Spec to be reviewed: CSS Color Adjust Level 1
* URL of spec: https://www.w3.org/TR/css-color-adjust-1/
* Issue to be re-reviewed: https://github.com/w3c/csswg-drafts/issues/5710
* Specific comment containing our response to be reviewed: https://github.com/w3c/csswg-drafts/issues/5710#issuecomment-840772752
* Previous Privacy Review request: <https://lists.w3.org/Archives/Public/www-style/2020Dec/0004.html> (currently no formal response, but @mallory filed https://github.com/w3c/csswg-drafts/issues/5548 which was duped to the issue in question, 5710)
* Overall feature definition is the intersection of <https://drafts.csswg.org/css-color-adjust/#forced> and <https://drafts.csswg.org/css-color-4/#css-system-colors>

Please file any responses as comments on the linked issue.

**Comment by pes10k** [comment]
@tabatkins is this a request for a complete new review, or just ongoing discussion about an issue that was raised during a previous review.  If the latter (my understanding) then another full PING review isn't needed, and the best way to proceed is to continue the discussion on the issue you linked to.  I'll encourage PING folks to participate in the discussion (I see @npdoty is involved already) too.

Ill close this issue now, though if i've misunderstood anything in the above, please let reopen.  Thanks!

**Comment by tabatkins** [comment]
Likely ongoing discussion about the issue raised in a previous review (tho as noted, we didn't get an official review response, so it's not quite clear...).

**Comment by pes10k** [comment]
Understood, and apologies for the silence about the previous review response.  It looks like a wire must have gotten crossed after the previous review.  I will make sure it doesn't happen again, and that PING works through the issue with you, in https://github.com/w3c/csswg-drafts/issues/5710#issuecomment-840772752
