### ISSUE TITLE
Resource Timing 2021-06-02 > 2021-06-23

### ISSUE THREAD

**Issue by caribouW3** [w3cping/privacy-request#42]
- name of spec to be reviewed: Resource Timing 
- URL of spec: https://w3c.github.io/resource-timing/ 

- What and when is your next expected transition? 
https://github.com/w3c/transitions/issues/337#issuecomment-850633515
Wide review was done in 2017. The Director is requesting a formal wide review with the most recent horizontal review process.

- What has changed since any previous review? 
In comparison to previously published "level 1" (in CR), changes are mainly
the addition of the size attributes, better buffering algorithms and Fetch integration.
We plan to drop levels and use a living standard development model (from process2020).
In comparison to previously published "level 1" (in CR), changes are mainly
the addition of the size attributes, better buffering algorithms and Fetch integration.

- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further.
https://w3c.github.io/resource-timing/#sec-privacy-security

- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
https://w3c.github.io/perf-security-privacy/

- Where and how to file issues arising?
https://github.com/w3c/resource-timing/issues/
 
- Pointer to any explainer for the spec? 
https://w3c.github.io/resource-timing/#introduction

Other comments:

**Comment by kdzwinel** [comment]
👋 Just FYI this API already had a privacy review over a year ago and I opened following issues:

https://github.com/w3c/resource-timing/issues/221
https://github.com/w3c/resource-timing/issues/222
https://github.com/w3c/resource-timing/issues/223

Maybe second request is totally fine, I'm not 100% sure about the procedure, but wanted to make sure that you are aware of this.

**Comment by caribouW3** [comment]
Indeed, those 3 issues were already indicated in the [CR transition request](https://github.com/w3c/transitions/issues/337) under the wide review section. The Director has requested for another wide review, though.

**Comment by sandandsnow** [comment]
Discussed during PING meeting on [1 July 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210701)

**Comment by sandandsnow** [comment]
Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
