### ISSUE TITLE
User Timing 2021-06-02 > 2021-06-23

### ISSUE THREAD

**Issue by caribouW3** [w3cping/privacy-request#43]
- name of spec to be reviewed: User Timing 
- URL of spec: https://w3c.github.io/user-timing/ 

- What and when is your next expected transition? 
https://github.com/w3c/transitions/issues/338#issuecomment-850636248
Wide review was already done for level 2. The WG wants to drop levels and merge level 3 in it.
The Director is requesting a formal wide review with the most recent horizontal review process.

- What has changed since any previous review? 
In level 3, addition of ability to execute marks and measures across arbitrary timestamps and
support for reporting arbitrary metadata along with marks and measures.

- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further.
https://w3c.github.io/user-timing/#privacy-security

- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
https://w3c.github.io/perf-security-privacy/

- Where and how to file issues arising?
https://github.com/w3c/user-timing/issues/
 
- Pointer to any explainer for the spec? 
https://w3c.github.io/user-timing/#introduction

Other comments:

**Comment by sandandsnow** [comment]
Review discussed on PING call on [15 July 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210715).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
