### ISSUE TITLE
Performance Timeline 2021-06-07 > 2021-06-28

### ISSUE THREAD

**Issue by caribouW3** [w3cping/privacy-request#44]
- name of spec to be reviewed: Performance Timeline
- URL of spec: https://w3c.github.io/performance-timeline/

- What and when is your next expected transition? 
https://github.com/w3c/transitions/issues/339#issuecomment-850639142
Wide review was done in 2016 for its previous CR.
The Director is requesting a formal wide review with the most recent horizontal review process.

- What has changed since any previous review? 
Previous CR was https://www.w3.org/TR/2016/CR-performance-timeline-2-20161208/
There is no fundamental change to the goals of the spec. The processing model is more detailed and 
data structure updated.
We plan to drop levels and use a living standard development model (from process2020).

- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further.
https://w3c.github.io/performance-timeline/#privacy-security

- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
https://w3c.github.io/perf-security-privacy/

- Where and how to file issues arising?
https://github.com/w3c/performance-timeline/
 
- Pointer to any explainer for the spec? 
https://w3c.github.io/performance-timeline/#introduction

**Comment by sandandsnow** [comment]
Review discussed on PING call on [15 July 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210715).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Closing issue as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
