### ISSUE TITLE
MediaStream Image Capture 2021-06-22 > 2021-07-22

### ISSUE THREAD

**Issue by caribouW3** [w3cping/privacy-request#45]
- name of spec to be reviewed: MediaStream Image Capture

- URL of spec: https://w3c.github.io/mediacapture-image/

- What and when is your next expected transition? not yet defined

- What has changed since any previous review? this is a 1st review

- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further.
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
https://github.com/w3c/mediacapture-image/blob/main/security-privacy-questionnaire.md

- Where and how to file issues arising?
https://github.com/w3c/mediacapture-image

- Pointer to any explainer for the spec?
https://github.com/w3c/mediacapture-image/blob/main/explainer.md

**Comment by pes10k** [comment]
The following issues were filed as part of this review

https://github.com/w3c/mediacapture-image/issues/283
https://github.com/w3c/mediacapture-image/issues/284
https://github.com/w3c/mediacapture-image/issues/285
https://github.com/w3c/mediacapture-image/issues/286

**Comment by sandandsnow** [comment]
Review discussed on PING call on [15 July 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210715).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
