### ISSUE TITLE
Request review for the HTML Review Draft — Published 18 January 2021 -> 2021-08-24

### ISSUE THREAD

**Issue by siusin** [w3cping/privacy-request#47]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: HTML Review Draft — Published 18 January 2021
- URL of spec: https://html.spec.whatwg.org/review-drafts/2021-01/

- What and when is your next expected transition? CR, 2021-08-24
- What has changed since any previous review?
  Please look at the [list of important changes](https://github.com/w3c/htmlwg/issues/17).
- Where and how to file issues arising?
  Please file an issue via https://github.com/whatwg/html/issues.

Other comments:
Thank you!

**Comment by sandandsnow** [comment]
To be discussed in PING call on 5 August 2021
