### ISSUE TITLE
Incremental Font Transfer 2021-11-10

### ISSUE THREAD

**Issue by svgeesus** [w3cping/privacy-request#61]
The Privacy IG prefers groups to complete a self-review around the time of FPWD. See https://w3ctag.github.io/security-questionnaire/.

If you still want us to review your spec, please provide the information below.

In the issue title above add the document name followed by the date of this request.

- name of spec to be reviewed: **Incremental Font Transfer**
- URL of spec: https://w3c.github.io/IFT/
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, correct that before proceeding further. [Yes, here it is](https://w3c.github.io/IFT/Overview.html#priv)
- Do you need a reply by a particular date? No, we recently went to FPWD, this is an early review, so no rush
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973) [self review](https://github.com/w3c/IFT/issues/35)
- Where and how to file issues arising? As separate issues under https://github.com/w3c/IFT please
- Pointer to any explainer for the spec? https://www.w3.org/TR/PFE-evaluation/

Other comments:

**Comment by samuelweiler** [comment]
I filed two issues already:

https://github.com/w3c/IFT/issues/42
https://github.com/w3c/IFT/issues/43

**Comment by samuelweiler** [comment]
Assigned to @pes10k

**Comment by pes10k** [comment]
the following issues were filed as a result of this review:

- https://github.com/w3c/IFT/issues/49
- https://github.com/w3c/IFT/issues/50
- https://github.com/w3c/IFT/issues/51

**Comment by jyasskin** [comment]
w3c/IFT#69 is relevant to the fetch() integration.

**Comment by sandandsnow** [comment]
Review discussed on PING call on [18 November 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20211118).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue is closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)

**Comment by svgeesus** [comment]
An [updated WD of IFT has been published](https://www.w3.org/TR/2022/WD-IFT-20220628/) which puts into one specification the Range Request and Patch-subset methods, and describes how client and server negotiate which method to use. Please base your review on this new /TR draft. Thanks!

**Comment by svgeesus** [comment]
A [new WD of IFT](https://www.w3.org/TR/2024/WD-IFT-20240709/) is available. This addresses review feedback from the earlier proposals. There is no longer a Range Request vs Patch Subset choice, and there is no longer any special protocol required. Compared to the earlier proposals, the risks of fingerprinting have been reduced ()see [Privacy Considerations](https://www.w3.org/TR/2024/WD-IFT-20240709/#priv) and there should no longer be an impact on CDN caching.

Because this is a substantial rewrite, we have [a new Explainer](https://github.com/w3c/IFT/blob/main/IFT-Explainer.md)

Review of this new draft from a Privacy perspective is warmly invited.
