### ISSUE TITLE
IMSC-HRM 2021-12-07

### ISSUE THREAD

**Issue by himorin** [w3cping/privacy-request#65]
We have conducted a self-review of our spec [IMSC-HRM](https://www.w3.org/TR/imsc-hrm/) ([ED](https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html)), and the results can be found at [IMSC-HRM self check result](https://github.com/w3c/imsc-hrm/issues/19).

Please check our findings.

- Do you need a reply by a particular date? : no particular date (expecting standard period like 2mo, but understand there is long holidays within)

Other comments:

- we expect no much change from FPWD, and wiling to enter CR relatively shortly without large number of  substantive changes
- original text was in TTML-IMSC specification, and cutted HRM section out for easier maintenance and upgrade

**Comment by himorin** [comment]
diff from initial text (cut out from existing IMSC 1.2 spec) to current text:
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fimsc-hrm%2F694ab17c5b8d571db74529689e41b23453c3b6f8%2Fspec%2Fimsc-hrm.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fimsc-hrm%2Fmain%2Fspec%2Fimsc-hrm.html

**Comment by pes10k** [comment]
The following issues were filed as part of this review:
- https://github.com/w3c/imsc-hrm/issues/28
- https://github.com/w3c/imsc-hrm/issues/29
- https://github.com/w3c/imsc-hrm/issues/30
- https://github.com/w3c/imsc-hrm/issues/31

**Comment by sandandsnow** [comment]
Review discussed on PING call on [6 January 2022](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20220106).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue is closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
