### ISSUE TITLE
CSS Conditional 4 2022-01-14 > 2022-03-14

### ISSUE THREAD

**Issue by svgeesus** [w3cping/privacy-request#70]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: **CSS Conditional Rules Module Level 4**
- URL of spec: [https://www.w3.org/TR/css-conditional-4/](https://www.w3.org/TR/css-conditional-4/)

- What and when is your next expected transition?
  - Candidate Recommendation
- What has changed since any previous review?
  - Since the [previous horizontal review of CSS Conditional 3](https://github.com/w3c/csswg-drafts/issues/5569) one new feature has been added, as described below.
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further. **[Yes](https://www.w3.org/TR/css-conditional-4/#privacy)**
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
  - The only parts of the self-review that seem to apply to this specification are regarding what information is exposed, and is it the minimum. The answers are  **[in the Privacy Considerations](https://www.w3.org/TR/css-conditional-4/#privacy)**
- Where and how to file issues arising?
  - As an [issue in our GitHub, please](https://github.com/w3c/csswg-drafts/labels/css-conditional-4)
- Pointer to any explainer for the spec?
  - [Explainer for `selector()` in `@supports`](https://github.com/dbaron/css-supports-functions/blob/main/explainer.md) by L. David Baron

Other comments:

This is currently a delta specification to [CSS Conditional 3](); the plan is to copy in all of that spec into this one, but currently this very short spec just has the one new feature relative to Level 3.

CSS Conditional 3 already has the ability to test whether CSS properties and property values are supported, before using them. This specification adds the ability to test of Selectors as well.

This specification, currently a Working Draft, is being advanced to CR soon because [all modern browsers now support it](https://caniuse.com/mdn-css_at-rules_supports_selector)

The published /TR specification does not have an example. Sorry! The [explainer](https://github.com/dbaron/css-supports-functions/blob/main/explainer.md) does, and one was also [just added to the ED](https://drafts.csswg.org/css-conditional-4/) plus test suite coverage. Apart from that, the /TR and ED are identical.

**Comment by jyasskin** [comment]
<This review hasn't been ratified by the whole PING yet>

The new feature has a good privacy considerations section that points out that it exposes the UA version and the value of any UA settings that turn on or off selectors. Point 2 of https://github.com/w3cping/privacy-request/issues/18#issuecomment-724390170 is still relevant, but it seems easier to detect whether a selector is supported in the current configuration of the UA, so there's even less concern about using @supports to also detect that fact. So, no concerns here.

**Comment by sandandsnow** [comment]
The privacy review of this spec will be discussed by PING in its meeting on 20 January 2022.

**Comment by npdoty** [comment]
Seemed like general agreement of @jyasskin 's assessment. Notes here: https://www.w3.org/Privacy/IG/summaries/PING-minutes-20220120

**Comment by sandandsnow** [comment]
Review discussed on PING call on 20 January 2022.

Issue closed as the review has been undertaken.
