### ISSUE TITLE
CSS Variables 2022-02-08 > 2022-04-08

### ISSUE THREAD

**Issue by svgeesus** [w3cping/privacy-request#79]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: **CSS Custom Properties for Cascading Variables Module Level 1** or, for short, CSS Variables
- URL of spec: https://www.w3.org/TR/css-variables-1/

- What and when is your next expected transition?
  This spec has [been in CR since 2015](https://www.w3.org/standards/history/css-variables-1) and is widely implemented. We are preparing a second CR Snapshot before moving to Proposed Recommendation.

- What has changed since any previous review?
  [Changes Since the 03 December 2015 CR](https://www.w3.org/TR/css-variables-1/#changes-20151203)

- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further.
  Yes

- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973)
  [Here](https://github.com/w3c/csswg-drafts/issues/6808#issuecomment-1033173803)

- Where and how to file issues arising?
  As individual issues on [CSSWG Github](https://github.com/w3c/csswg-drafts/issues)

- Pointer to any explainer for the spec? [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

Other comments:

This specification is used for passing information around in a stylesheet so that it can be re-used. It is also used as an interface between scripting and styling.

**Comment by pes10k** [comment]
Review was discussed on PING call on February 17. No issues to report so closing the review out.  Thanks!
