### ISSUE TITLE
WIP: Web of Things (WoT) Discovery 2022-04-27 > 2022-08-30

### ISSUE THREAD

**Issue by mmccool** [w3cping/privacy-request#83]
WIP: Still finalizing some details, please do not start review until WIP removed from title. In particular, finalizing explainer link in the below, that will be done soon.

- Name of spec to be reviewed: 
    * Web of Things (WoT) Discovery
- URL of spec: 
    * Editor's: https://w3c.github.io/wot-discovery/
    * Last published: https://www.w3.org/TR/wot-discovery/
- What and when is your next expected transition?
    * The CR transition is planned for 30 August 2022
- What has changed since any previous review?
    * First review
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  
    * Yes
- Please point to the results of your own self-review:
    * https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md
- Where and how to file issues arising?
    * As an [issue in our GitHub](https://github.com/w3c/wot-discovery/issues), please 
- Pointer to any explainer for the spec?
   * WIP

Other comments:

**Comment by samuelweiler** [comment]
@mmccool  Could the WG publish a working draft snapshot? We like to be able to have a stable link when we review - so that it's relatively easy to see what the document looked like at the time of review and be able to track changes after that point.

**Comment by sandandsnow** [comment]
Review discussed on PING call on [5 May 2022](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20220505)

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)

**Comment by mmccool** [comment]
We feel that we have addressed the privacy considerations that were raised, can PING please confirm?

**Comment by harrisonsean** [comment]
PING confirmed
