### ISSUE TITLE
Web of Things (WoT) Thing Description 1.1 2022-04-27 > 2022-05-15

### ISSUE THREAD

**Issue by sebastiankb** [w3cping/privacy-request#84]
- name of spec to be reviewed: Web of Things (WoT) Thing Description 1.1
- URL of spec: https://www.w3.org/TR/wot-thing-description11/

- What and when is your next expected transition? 
  - The CR transition is planned for mid-May, 2022
  
- What has changed since any previous review? 
  - this is the first submitted version for Thing Description 1.1
  - the change log to the Thing Description 1.0 can be found [here](https://w3c.github.io/wot-thing-description/#changes)
  
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  
  - yes, please see https://www.w3.org/TR/wot-thing-description11/#sec-privacy-consideration
 
- Please point to the results of your own self-review
  - https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md

- Where and how to file issues arising? 
  - As an [issue in our GitHub](https://github.com/w3c/wot-thing-description/issues), please
  
- Pointer to any explainer for the spec? 
  - https://github.com/w3c/wot-thing-description/blob/main/explainer/Explainer11.md

Other comments:

Many thanks :-)

**Comment by sandandsnow** [comment]
PING is planning to discuss this privacy request at its next meeting on 5 May 2022.

**Comment by sandandsnow** [comment]
Review discussed on PING call on [5 May 2022](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20220505)

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)

**Comment by mmccool** [comment]
We feel that we have addressed the privacy considerations that were raised, can PING please confirm?

**Comment by harrisonsean** [comment]
PING confirmed
