### ISSUE TITLE
WebGPU 2022-04-29

### ISSUE THREAD

**Issue by toji** [w3cping/privacy-request#85]
(Note: The WebGPU spec [transitioned to FPWD](https://github.com/w3c/transitions/issues/333) a little while ago, but we wouldn't consider a transition to CR imminent, so this seemed like the better template. Happy to accommodate any additional information that's requested!)

- Spec to be reviewed: **WebGPU**
- Recent Spec Snapshot: https://www.w3.org/TR/2022/WD-webgpu-20220526/ 
- URL of spec (Editor's Draft): https://gpuweb.github.io/gpuweb/
  - [Privacy Considerations section](https://gpuweb.github.io/gpuweb/#privacy-considerations)
  - [Security Considerations section](https://gpuweb.github.io/gpuweb/#security-considerations)
- We don't have a specific date required for a reply, but browser vendors would like to ship the feature later this year. 
- [Privacy and Security self-review](https://gpuweb.github.io/gpuweb/explainer/#questionnaire) is available in the explainer.
- Please [file issues with the spec repo](https://github.com/gpuweb/gpuweb/issues). Either separate or bulk issues are acceptable.
- Supplementary documents:
  - [Spec explainer](https://gpuweb.github.io/gpuweb/explainer/)
  - [Various design docs](https://github.com/gpuweb/gpuweb/tree/main/design)

Other comments:
- The design of the Adapter Identifiers portion of the API is still considered in-progress and is likely of special interest to the PING. We would specifically appreciate feedback on it as a result:
  - [Adapter Identifier Design Doc](https://github.com/gpuweb/gpuweb/blob/main/design/AdapterIdentifiers.md)
  - Relevant spec sections: [1](https://www.w3.org/TR/2022/WD-webgpu-20220526/#gpu-adapterinfo), [2](https://www.w3.org/TR/2022/WD-webgpu-20220526/#dom-gpuadapter-requestadapterinfo)
- The WGSL shading language, which has [it's own spec.](https://gpuweb.github.io/gpuweb/wgsl/), is a critical part of WebGPU. The security and privacy considerations for both specs are addressed in the primary WebGPU spec, linked above.

**Comment by samuelweiler** [comment]
@toji Could the WG publish a working draft snapshot? We like to be able to have a stable link when we review - so that it's relatively easy to see what the document looked like at the time of review and be able to track changes after that point.

**Comment by toji** [comment]
+ @cwallez, @kdashg

Working draft is at https://www.w3.org/TR/webgpu/, but I believe it auto-updates. We'll look into making a snapshot.

**Comment by kainino0x** [comment]
The auto-publishing keeps snapshots - see the link at the top of the live draft:
https://www.w3.org/TR/2022/WD-webgpu-20220505/

**Comment by sandandsnow** [comment]
Update: We're still trying to locate someone, ideally with some GPU expertise, to undertake the review.

**Comment by toji** [comment]
Thanks for the update! Also, please note that the above referenced Adapter Identifiers section of the API has now been merged and is part of the most recent snapshots, such as https://www.w3.org/TR/2022/WD-webgpu-20220526/. I recommend using that as the basis for your review, and have updated the initial comment to reflect that.

**Comment by Kangz** [comment]
> Update: We're still trying to locate someone, ideally with some GPU expertise, to undertake the review.

There are a ton of GPU experts in the WebGPU group :) If that helps we could have a more interactive formats: have a meeting with the WebGPU group (or multiple if need be) where the PING can ask any questions they might have on GPUs to help with the review.

**Comment by pes10k** [comment]
I have filed these two issues as a result of this review:
- https://github.com/gpuweb/gpuweb/issues/3101
- https://github.com/gpuweb/gpuweb/issues/3102

**Comment by jyasskin** [comment]
This was further discussed at https://github.com/w3c/ping/blob/main/summaries/PING-minutes-20230706.md#1-webgpu.
