### ISSUE TITLE
Web of Things (WoT) Architecture 1.1 2022-05-03 > 2022-06-30

### ISSUE THREAD

**Issue by mmccool** [w3cping/privacy-request#86]
Ready to review.  Please review the editor's draft, we are working on publishing an update.

- Name of spec to be reviewed:
    - Web of Things (WoT) Architecture
- URL of spec:
    * Editor's: https://w3c.github.io/wot-architecture/
    * Last published: https://www.w3.org/TR/wot-architecture11/
- What and when is your next expected transition?
    * The CR transition is planned for 30 June 2022
- What has changed since any previous review?
    * See change log; updates to cover new deliverables, including Discovery
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  
    * Yes
- Please point to the results of your own self-review:
    * https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md
- Where and how to file issues arising?
    * As an [issue in our GitHub](https://github.com/w3c/wot-architecture/issues), please 
- Pointer to any explainer for the spec?
    * https://github.com/w3c/wot-architecture/blob/main/explainer/explainer11.md

Other comments:

**Comment by samuelweiler** [comment]
@mmccool Could the WG publish a WD for purposes of review?  (We like to be able to have a stable link when we review - so that it's relatively easy to see what the document looked like at the time of review and be able to track changes after that point.)

**Comment by sandandsnow** [comment]
PING is planning to discuss this review in its meeting on 19 May 2022

**Comment by sandandsnow** [comment]
Review discussed on PING call on [19 May 2022](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20220519).

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
