### ISSUE TITLE
WebXR Gamepads Module Level 1 2021-05-23 > 2021-07-23

### ISSUE THREAD

**Issue by himorin** [w3cping/privacy-request#89]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: WebXR Gamepads Module - Level 1
- URL of spec: https://www.w3.org/TR/2022/WD-webxr-gamepads-module-1-20220426/

- What and when is your next expected transition? as soon as HR finished
- What has changed since any previous review? first privacy review
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  yes
- Please point to the results of your own self-review https://github.com/immersive-web/webxr-gamepads-module/issues/56
- Where and how to file issues arising? https://github.com/immersive-web/webxr-gamepads-module/issues
- Pointer to any explainer for the spec? https://github.com/immersive-web/webxr-gamepads-module/blob/main/gamepads-module-explainer.md

Other comments:

**Comment by himorin** [comment]
hi @IreneKnapp , if there is any update on this review like some issues found, please kindly let us inform. (I believe we have not received any issue filed against our repository.)

**Comment by IreneKnapp** [comment]
Thanks for that. The review was done some time ago and there were no issues found; from my perspective as the reviewer you are free to go forward. It's been a while since I've done one of these and I'm not certain what procedures PING has to make that official.

**Comment by pes10k** [comment]
okie closing this issue since @IreneKnapp gives it the 👍 .  Thanks!
