### ISSUE TITLE
DCAT 3 2022-05-10

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3cping/privacy-request#90]
We have conducted a self-review of our spec [DCAT 3](https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/), and the results can be found at https://github.com/w3c/dxwg/issues/1507.

Please check our findings.

- Do you need a reply by a particular date?
End of August, Early September as we plan to move to CR in Autumn.

**Comment by npdoty** [comment]
will work with @LubnaDajani on this review

**Comment by npdoty** [comment]
Chatted with PING about this today.
Opened https://github.com/w3c/dxwg/issues/1524, https://github.com/w3c/dxwg/issues/1525, https://github.com/w3c/dxwg/issues/1526. 
Emailed the WG with review.
