### ISSUE TITLE
WebXR AR Module Level 1 2021-05-27 > 2021-07-27

### ISSUE THREAD

**Issue by himorin** [w3cping/privacy-request#91]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: WebXR Augmented Reality Module - Level 1
- URL of spec: https://www.w3.org/TR/2022/WD-webxr-ar-module-1-20220426/

- What and when is your next expected transition? as soon as HR finished
- What has changed since any previous review? this is first review request
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  If not, corrrect that before proceeding further. [yes](https://www.w3.org/TR/2022/WD-webxr-ar-module-1-20220426/#privacy-security)
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973) https://github.com/immersive-web/webxr-ar-module/issues/85
- Where and how to file issues arising? https://github.com/immersive-web/webxr-ar-module/issues
- Pointer to any explainer for the spec? https://github.com/immersive-web/webxr-ar-module/blob/main/ar-module-explainer.md

Other comments:

**Comment by himorin** [comment]
hi @Sauski , if there is any update on this review like some issues found, please kindly let us inform.

**Comment by Sauski** [comment]
Apologies for the delay! We discussed this as part of our meeting on the 16th of June [meeting notes here](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20220616). No blocking concerns were raised. 

Following up on the [appendix issue here](https://github.com/immersive-web/webxr/issues/754) would be a good future step for the team, and certainly make future privacy reviewers easier by making the information delta between modules more accessible.
