### ISSUE TITLE
MiniApp Lifecycle 2022-06-08 > 2022-09-08

### ISSUE THREAD

**Issue by xfq** [w3cping/privacy-request#93]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: MiniApp Lifecycle
- URL of spec: https://www.w3.org/TR/2022/WD-miniapp-lifecycle-20220528/

- What and when is your next expected transition? CR in September 2022
- What has changed since any previous review? This is the first formal privacy review request.
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  Yes.
- Please point to the results of your own self-review: https://github.com/w3c/miniapp-lifecycle/issues/27#issuecomment-1148451911
- Where and how to file issues arising? https://github.com/w3c/miniapp-lifecycle/issues
- Pointer to any explainer for the spec? https://github.com/w3c/miniapp-lifecycle/blob/main/docs/explainer.md

Other comments:

See also the [MiniApp Standardization White Paper](https://www.w3.org/TR/mini-app-white-paper/).

**Comment by pes10k** [comment]
I've completed this review, and filed these three issues as a result:

- https://github.com/w3c/miniapp-lifecycle/issues/30
- https://github.com/w3c/miniapp-lifecycle/issues/31
- https://github.com/w3c/miniapp-lifecycle/issues/32
