### ISSUE TITLE
Baggage 2022-06-08

### ISSUE THREAD

**Issue by kalyanaj** [w3cping/privacy-request#94]
- name of spec to be reviewed:  W3C Baggage
- URL of spec: https://www.w3.org/TR/baggage/ 
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations? Yes
- Do you need a reply by a particular date?   Yes, we are looking to move this spec to the CR stage in the next few months, so a reply by end of June will be helpful to be able to react to any issues filed.
- Please point to the results of your own self-review: https://github.com/w3c/baggage/issues/95
- Where and how to file issues arising? https://github.com/w3c/baggage/issues
- Pointer to any explainer for the spec? https://github.com/w3c/baggage/blob/main/baggage/README.md provides an overview and the use cases.

**Comment by pes10k** [comment]
I've completed this review, and filed these three issues as a result:
- https://github.com/w3c/baggage/issues/105
- https://github.com/w3c/baggage/issues/106
- https://github.com/w3c/baggage/issues/107
