### ISSUE TITLE
Core-AAM 2022-06-21 > 2022-07-29

### ISSUE THREAD

**Issue by michael-n-cooper** [w3cping/privacy-request#95]
In the issue title above add the document name followed by the date of this request, then the date of your proposed deadline for comments.

- name of spec to be reviewed: Core-AAM 1.2
- URL of spec: https://w3c.github.io/core-aam/

- What and when is your next expected transition? Q3 2022 entering CRD
- What has changed since any previous review? see https://w3c.github.io/core-aam/#changelog - mapping changes for WAI-ARIA role, state, and property changes
- Please point to the results of your own self-review: https://github.com/w3c/core-aam/issues/125)
- Where and how to file issues arising? https://github.com/w3c/core-aam/issues
- Pointer to any explainer for the spec? http://www.w3.org/TR/wai-aria-roadmap/

Other comments:

**Comment by sandandsnow** [comment]
This will be discussed at the PING meeting on 1 September 2022.

**Comment by npdoty** [comment]
I've opened https://github.com/w3c/core-aam/issues/154 and https://github.com/w3c/core-aam/issues/155 to summarize the privacy review feedback on this spec.

Thanks @sseng123 for doing the initial review and PING for helping to consider the topic. I hope those two github issues distill the basic ideas that were raised, but Joshua or others feel free to elaborate on them if I missed something.
