### ISSUE TITLE
MiniApp Manifest 2022-07-01 > 2022-10-01

### ISSUE THREAD

**Issue by xfq** [w3cping/privacy-request#97]
- name of spec to be reviewed: MiniApp Manifest
- URL of spec: https://www.w3.org/TR/2022/WD-miniapp-manifest-20220517/

- What and when is your next expected transition? CR in October 2022
- What has changed since any previous review? This is the first formal privacy review request.
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations?  Yes.
- Please point to the results of your own self-review: https://github.com/w3c/miniapp-manifest/blob/main/docs/security-privacy-questionnaire.md
- Where and how to file issues arising? https://github.com/w3c/miniapp-manifest/issues
- Pointer to any explainer for the spec? https://github.com/w3c/miniapp-manifest/blob/main/docs/explainer.md

Other comments:

See also the [MiniApp Standardization White Paper](https://www.w3.org/TR/mini-app-white-paper/).

**Comment by pes10k** [comment]
I've completed this review, and filed these three issues as a result:

- https://github.com/w3c/miniapp-manifest/issues/54
- https://github.com/w3c/miniapp-manifest/issues/55
- https://github.com/w3c/miniapp-manifest/issues/56
