### ISSUE TITLE
WCAG 2.2 2022-07-29 > 2022-08-26

### ISSUE THREAD

**Issue by michael-n-cooper** [w3cping/privacy-request#98]
- name of spec to be reviewed: Web Content Accessibility Guidelines 2.2
- URL of spec: https://w3c.github.io/wcag/guidelines/22/

- What and when is your next expected transition? CR, as soon as reviews complete
- What has changed since any previous review? https://w3c.github.io/wcag/guidelines/22/#new-features-in-wcag-2-2
- Please point to the results of your own self-review pending
- Where and how to file issues arising? https://github.com/w3c/wcag/issues
- Pointer to any explainer for the spec? https://www.w3.org/WAI/standards-guidelines/wcag/

Other comments:

The Working Group thinks this version of WCAG does not introduce new privacy considerations.

**Comment by wseltzer** [comment]
Privacy consideration filed https://github.com/w3c/wcag/issues/2615
