### ISSUE TITLE
MiniApp Packaging 2022-08-02 > 2022-11-02

### ISSUE THREAD

**Issue by xfq** [w3cping/privacy-request#99]
- name of spec to be reviewed: MiniApp Packaging
- URL of spec: https://www.w3.org/TR/2022/WD-miniapp-packaging-20220729/

- What and when is your next expected transition? CR in November 2022
- What has changed since any previous review? This is the first formal privacy review request.
- Does your document have an in-line Privacy Considerations section, ideally one separate from the Security Considerations? Yes.
- Please point to the results of your own self-review: https://github.com/w3c/miniapp-packaging/blob/main/docs/security-privacy-questionnaire.md
- Where and how to file issues arising? https://github.com/w3c/miniapp-packaging/issues
- Pointer to any explainer for the spec? https://github.com/w3c/miniapp-packaging/blob/main/docs/explainer.md

Other comments:

See also the [MiniApp Standardization White Paper](https://www.w3.org/TR/mini-app-white-paper/).

**Comment by pes10k** [comment]
Closing this review now.  I've filed the following issues

- https://github.com/w3c/miniapp-packaging/issues/60
- https://github.com/w3c/miniapp-packaging/issues/61
- https://github.com/w3c/miniapp-packaging/issues/62 (Needs resolution)
